# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import drfpasswordless.models


class Migration(migrations.Migration):

    dependencies = [
        ('drfpasswordless', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='CallbackToken',
            name='key',
            field=models.CharField(default=drfpasswordless.models.generate_hex_token, max_length=32, unique=True)
        ),
    ]

